#!/usr/bin/env bash

make -C checker 2>&1 > /dev/null
make -C comb_gen 2>&1 > /dev/null
make -C push_swap 2>&1 > /dev/null

comb_size=1
comb_count=0
len="0"
total_len="0"
avg="0"

function test_combo () {
	inst=$(push_swap/push_swap $1)
	if [ $(echo -n "$inst" | checker/checker $1) == "OK" ]; then
		len="$(echo -n "$inst" | wc -w | tr -d '[:space:]')"
		echo "found solution in $len instructions"
	else
		echo "invalid solution :("
		echo "$inst"
		exit 1
	fi
}

while [ $comb_size -lt 6 ]; do
	combs=$(comb_gen/comb_gen $comb_size)
	while read line; do
		echo -n "Testing with '$line': "
		test_combo "$line"
		total_len=$(echo $total_len+$len | bc)
		comb_count=$((comb_count+1))
	done <<< "$combs"
	if [ $comb_count -gt 1 ]; then
		comb_count=$((comb_count-1))
		avg=$(echo 'scale=4;'$total_len/$comb_count | bc)
	fi
	echo "Sorted lists of $comb_size numbers in an average of $avg instructions."
	total_len="0"
	avg="0"
	comb_count=0
	comb_size=$((comb_size+1))
done

comb_size=100
comb_count=30
avg="0"
i=0

while [ $i -lt $comb_count ]; do
	comb=$(gshuf -i 0-150 -n $comb_size | tr "\n" " ")
	test_combo "$comb"
	total_len=$(echo $total_len+$len | bc)
	i=$((i+1))
done

avg=$(echo 'scale=4;'$total_len/$comb_count | bc)
echo "total_len = $total_len; comb_count = $comb_count"
echo "Sorted lists of $comb_size numbers in an average of $avg instructions."

comb_size=500
comb_count=30
avg="0"
i=0

while [ $i -lt $comb_count ]; do
	comb=$(gshuf -i 0-10000 -n $comb_size | tr "\n" " ")
	test_combo "$comb"
	total_len=$(echo $total_len+$len | bc)
	i=$((i+1))
done

avg=$(echo 'scale=4;'$total_len/$comb_count | bc)
echo "total_len = $total_len; comb_count = $comb_count"
echo "Sorted lists of $comb_size numbers in an average of $avg instructions."
